const PDFDocument = require('pdfkit');

const generateReport = (contract, res) => {
  const doc = new PDFDocument({ margin: 50 });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="contractsense-report.pdf"`);
  doc.pipe(res);

  doc.fontSize(22).font('Helvetica-Bold')
     .text('ContractSense Analysis Report', { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(10).font('Helvetica').fillColor('#888888')
     .text(`Generated on ${new Date().toLocaleDateString()}`, { align: 'center' });
  doc.moveDown(1);

  doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#e5e7eb').stroke();
  doc.moveDown(1);

  doc.fontSize(11).font('Helvetica').fillColor('#374151')
     .text(`File: ${contract.fileName}`);
  doc.moveDown(1);

  const riskColor =
    contract.riskScore >= 70 ? '#ef4444' :
    contract.riskScore >= 40 ? '#f59e0b' : '#22c55e';

  doc.fontSize(14).font('Helvetica-Bold').fillColor('#111827').text('Risk Score');
  doc.moveDown(0.3);
  doc.fontSize(32).font('Helvetica-Bold').fillColor(riskColor)
     .text(`${contract.riskScore}/100`);
  doc.moveDown(0.5);

  doc.fontSize(14).font('Helvetica-Bold').fillColor('#111827').text('Summary');
  doc.moveDown(0.3);
  doc.fontSize(11).font('Helvetica').fillColor('#374151')
     .text(contract.summary, { lineGap: 4 });
  doc.moveDown(1.5);

  doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#e5e7eb').stroke();
  doc.moveDown(1);

  doc.fontSize(14).font('Helvetica-Bold').fillColor('#111827')
     .text(`Clauses (${contract.clauses?.length || 0})`);
  doc.moveDown(0.8);

  contract.clauses?.forEach((clause, i) => {
    const color =
      clause.risk === 'high'   ? '#ef4444' :
      clause.risk === 'medium' ? '#f59e0b' : '#22c55e';

    doc.fontSize(12).font('Helvetica-Bold').fillColor('#111827')
       .text(`${i + 1}. ${clause.title} `, { continued: true })
       .fillColor(color).text(`[${clause.risk.toUpperCase()}]`);
    doc.moveDown(0.3);
    doc.fontSize(10).font('Helvetica-Oblique').fillColor('#6b7280')
       .text(`"${clause.text}"`, { lineGap: 3 });
    doc.moveDown(0.3);
    doc.fontSize(10).font('Helvetica').fillColor('#374151')
       .text(`${clause.explanation}`, { lineGap: 3 });
    doc.moveDown(0.3);
    doc.fontSize(10).font('Helvetica').fillColor('#16a34a')
       .text(`Suggestion: ${clause.suggestion}`, { lineGap: 3 });
    doc.moveDown(1);
  });

  if (contract.deadlines?.length > 0) {
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#e5e7eb').stroke();
    doc.moveDown(1);
    doc.fontSize(14).font('Helvetica-Bold').fillColor('#111827')
       .text(`Deadlines (${contract.deadlines.length})`);
    doc.moveDown(0.8);

    contract.deadlines.forEach(d => {
      doc.fontSize(11).font('Helvetica-Bold').fillColor('#374151')
         .text(`- ${d.label}: `, { continued: true })
         .font('Helvetica')
         .text(`${d.date} (${
           d.daysRemaining === null  ? 'invalid date' :
           d.daysRemaining < 0      ? `expired ${Math.abs(d.daysRemaining)} days ago` :
           d.daysRemaining === 0    ? 'due today' :
           `${d.daysRemaining} days remaining`
         })`);
      doc.moveDown(0.5);
    });
  }

  doc.moveDown(2);
  doc.fontSize(9).font('Helvetica').fillColor('#9ca3af')
     .text('Generated by ContractSense', { align: 'center' });

  doc.end();
};

module.exports = { generateReport };